sudo: required
dist: precise
language: ruby
rvm:
  - 1.8.7-p374
  - 1.9.3
bundler_args: --local
before_script:
  - gem update --system 1.8.25
  - mysql -e 'create database pairwise_test;'
  - bundle exec rake db:schema:load
script: bundle exec rake cucumber spec
