language: ruby
rvm:
  - 1.8.7
  - 1.9.3
#bundler_args: --local
before_install:
  - gem update --system 1.8.25
before_script:
  - mysql -e 'create database pairwise_test;'
  - bundle exec rake db:schema:load
script: bundle exec rake cucumber spec
